"""Added connections to channels and users

Revision ID: a297bd1574a9
Revises: cc4ef9567c87
Create Date: 2025-09-03 12:29:20.074542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a297bd1574a9'
down_revision = 'cc4ef9567c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_channel_id'), ['channel_id'], unique=False)
        batch_op.create_foreign_key('fk_posts_id_to_channels_id', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_id_to_channels_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_channel_id'))
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
