"""Added a path column to channels to store their parentage

Revision ID: bbd769b4f129
Revises: a297bd1574a9
Create Date: 2025-09-03 16:40:59.746516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd769b4f129'
down_revision = 'a297bd1574a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Text(), nullable=False, server_default="[]"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
