"""Added a table for users to follow channels

Revision ID: cc4ef9567c87
Revises: 9e5c32e6c7e7
Create Date: 2025-09-03 10:47:33.564224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4ef9567c87'
down_revision = '9e5c32e6c7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_channel_follows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'channel_id')
    )
    with op.batch_alter_table('user_channel_follows', schema=None) as batch_op:
        batch_op.create_index('ix_ucf_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('ix_ucf_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_channel_follows', schema=None) as batch_op:
        batch_op.drop_index('ix_ucf_user_id')
        batch_op.drop_index('ix_ucf_channel_id')

    op.drop_table('user_channel_follows')
    # ### end Alembic commands ###
